module broker{
	module radio{

		interface Box_Monitor_Radio {
        		string GetUpdate ( in short num, out float time, out float metres );
			void Force_Pitstop ( in boolean force );
		};

		interface Competition_Monitor_Radio {
		        typedef sequence<float> float_sequence;

			string Get_CompetitorInfo(in short lap, in short sector, in short id, out float time, out float metres);
        		float_sequence Get_CompetitionInfo(in float timeInstant, out string xmlInfo);
		        boolean ready( in short competitorId );
	        	float Get_CompetitionConfiguration(inout string xmlConf);
	        	string Get_CompetitorConfiguration(in short id);
			void Set_Simulation_Speed(in float simulationSpeed);
			float Get_Latest_Time_Instant();
		};

		interface BoxRadio {
        		string RequestStrategy ( in short lap );
		};

	};
};
