package broker.radio;


/**
* broker/radio/_Box_Monitor_RadioStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../idl/radio.idl
* martedì 28 settembre 2010 12.09.37 CEST
*/

public class _Box_Monitor_RadioStub extends org.omg.CORBA.portable.ObjectImpl implements broker.radio.Box_Monitor_Radio
{

  public String GetUpdate (short num, org.omg.CORBA.FloatHolder time, org.omg.CORBA.FloatHolder metres)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("GetUpdate", true);
                $out.write_short (num);
                $in = _invoke ($out);
                String $result = $in.read_string ();
                time.value = $in.read_float ();
                metres.value = $in.read_float ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return GetUpdate (num, time, metres        );
            } finally {
                _releaseReply ($in);
            }
  } // GetUpdate

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:broker/radio/Box_Monitor_Radio:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.Object obj = org.omg.CORBA.ORB.init (args, props).string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     String str = org.omg.CORBA.ORB.init (args, props).object_to_string (this);
     s.writeUTF (str);
  }
} // class _Box_Monitor_RadioStub
