package broker.radio;


/**
* broker/radio/Box_Monitor_RadioHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../idl/radio.idl
* Monday, October 18, 2010 12:37:52 PM CEST
*/

abstract public class Box_Monitor_RadioHelper
{
  private static String  _id = "IDL:broker/radio/Box_Monitor_Radio:1.0";

  public static void insert (org.omg.CORBA.Any a, broker.radio.Box_Monitor_Radio that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static broker.radio.Box_Monitor_Radio extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (broker.radio.Box_Monitor_RadioHelper.id (), "Box_Monitor_Radio");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static broker.radio.Box_Monitor_Radio read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_Box_Monitor_RadioStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, broker.radio.Box_Monitor_Radio value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static broker.radio.Box_Monitor_Radio narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof broker.radio.Box_Monitor_Radio)
      return (broker.radio.Box_Monitor_Radio)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      broker.radio._Box_Monitor_RadioStub stub = new broker.radio._Box_Monitor_RadioStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static broker.radio.Box_Monitor_Radio unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof broker.radio.Box_Monitor_Radio)
      return (broker.radio.Box_Monitor_Radio)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      broker.radio._Box_Monitor_RadioStub stub = new broker.radio._Box_Monitor_RadioStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
