package broker.radio;


/**
* broker/radio/Box_Monitor_Radio.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../idl/radio.idl
* Thursday, September 23, 2010 6:33:06 PM CEST
*/

public interface Box_Monitor_Radio extends Box_Monitor_RadioOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Box_Monitor_Radio
