package broker.radio;


/**
* broker/radio/Box_Monitor_RadioOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../idl/radio.idl
* Monday, September 13, 2010 1:13:31 PM CEST
*/

public interface Box_Monitor_RadioOperations 
{
  String GetUpdate (short num, org.omg.CORBA.FloatHolder time, org.omg.CORBA.FloatHolder metres);
} // interface Box_Monitor_RadioOperations
