package broker.radio;


/**
* broker/radio/Box_Monitor_RadioOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../idl/radio.idl
* lunedì 11 ottobre 2010 16.12.43 CEST
*/

public interface Box_Monitor_RadioOperations 
{
  String GetUpdate (short num, org.omg.CORBA.FloatHolder time, org.omg.CORBA.FloatHolder metres);
  void Force_Pitstop (boolean force);
} // interface Box_Monitor_RadioOperations
