package broker.radio;


/**
* broker/radio/Box_Monitor_RadioOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../idl/radio.idl
* martedì 28 settembre 2010 12.39.28 CEST
*/

public interface Box_Monitor_RadioOperations 
{
  String GetUpdate (short num, org.omg.CORBA.FloatHolder time, org.omg.CORBA.FloatHolder metres);
} // interface Box_Monitor_RadioOperations
