package broker.radio;


/**
* broker/radio/BoxRadio.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../idl/radio.idl
* lunedì 11 ottobre 2010 16.12.43 CEST
*/

public interface BoxRadio extends BoxRadioOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface BoxRadio
