package broker.radio;


/**
* broker/radio/BoxRadio.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../idl/radio.idl
* martedì 28 settembre 2010 12.39.28 CEST
*/

public interface BoxRadio extends BoxRadioOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface BoxRadio
