package broker.radio;


/**
* broker/radio/BoxRadioOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../idl/radio.idl
* mercoledì 29 settembre 2010 17.09.52 CEST
*/

public interface BoxRadioOperations 
{
  String RequestStrategy (short lap);
} // interface BoxRadioOperations
