package broker.radio;


/**
* broker/radio/BoxRadioOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../idl/radio.idl
* giovedì 7 ottobre 2010 22.57.22 CEST
*/

public interface BoxRadioOperations 
{
  String RequestStrategy (short lap);
} // interface BoxRadioOperations
