package broker.radio;


/**
* broker/radio/Competition_Monitor_Radio.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../idl/radio.idl
* Thursday, September 23, 2010 1:31:48 AM CEST
*/

public interface Competition_Monitor_Radio extends Competition_Monitor_RadioOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Competition_Monitor_Radio
