package broker.radio;


/**
* broker/radio/Competition_Monitor_Radio.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../idl/radio.idl
* martedì 28 settembre 2010 12.39.28 CEST
*/

public interface Competition_Monitor_Radio extends Competition_Monitor_RadioOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Competition_Monitor_Radio
