
/**
* Configurator.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from configurator.idl
* Sunday, August 1, 2010 2:40:08 PM CEST
*/

public interface Configurator extends ConfiguratorOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Configurator
