
/**
* ConfiguratorOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from configurator.idl
* venerdì 20 agosto 2010 22.06.54 CEST
*/

public interface ConfiguratorOperations 
{
  String Configure (String config);
} // interface ConfiguratorOperations
