
/**
* ConfiguratorHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from configurator.idl
* venerdì 20 agosto 2010 22.06.54 CEST
*/

abstract public class ConfiguratorHelper
{
  private static String  _id = "IDL:Configurator:1.0";

  public static void insert (org.omg.CORBA.Any a, Configurator that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static Configurator extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (ConfiguratorHelper.id (), "Configurator");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static Configurator read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_ConfiguratorStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, Configurator value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static Configurator narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Configurator)
      return (Configurator)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      _ConfiguratorStub stub = new _ConfiguratorStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static Configurator unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Configurator)
      return (Configurator)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      _ConfiguratorStub stub = new _ConfiguratorStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
