
/**
* ConfiguratorOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from configurator.idl
* Sunday, August 1, 2010 2:40:08 PM CEST
*/

public interface ConfiguratorOperations 
{
  String Configure (String config);
} // interface ConfiguratorOperations
