
/**
* ConfiguratorHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from configurator.idl
* Sunday, August 1, 2010 2:40:08 PM CEST
*/

public final class ConfiguratorHolder implements org.omg.CORBA.portable.Streamable
{
  public Configurator value = null;

  public ConfiguratorHolder ()
  {
  }

  public ConfiguratorHolder (Configurator initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ConfiguratorHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ConfiguratorHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ConfiguratorHelper.type ();
  }

}
