
/**
* RegistrationHandler.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from registrationHandler.idl
* Monday, August 30, 2010 6:09:38 PM CEST
*/

public interface RegistrationHandler extends RegistrationHandlerOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface RegistrationHandler
