
/**
* RegistrationHandlerHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from registrationHandler.idl
* Monday, August 30, 2010 6:09:38 PM CEST
*/

abstract public class RegistrationHandlerHelper
{
  private static String  _id = "IDL:RegistrationHandler:1.0";

  public static void insert (org.omg.CORBA.Any a, RegistrationHandler that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static RegistrationHandler extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (RegistrationHandlerHelper.id (), "RegistrationHandler");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static RegistrationHandler read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_RegistrationHandlerStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, RegistrationHandler value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static RegistrationHandler narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof RegistrationHandler)
      return (RegistrationHandler)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      _RegistrationHandlerStub stub = new _RegistrationHandlerStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static RegistrationHandler unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof RegistrationHandler)
      return (RegistrationHandler)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      _RegistrationHandlerStub stub = new _RegistrationHandlerStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
