package broker.init;


/**
* broker/init/BoxConfigurator.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../idl/init.idl
* Tuesday, September 28, 2010 11:55:22 AM CEST
*/

public interface BoxConfigurator extends BoxConfiguratorOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface BoxConfigurator
