package broker.init;


/**
* broker/init/BoxConfiguratorOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../idl/init.idl
* domenica 26 settembre 2010 17.56.49 CEST
*/

public interface BoxConfiguratorOperations 
{
  String Configure (String config);
} // interface BoxConfiguratorOperations
