package broker.init;


/**
* broker/init/BoxConfigurator.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../idl/init.idl
* domenica 26 settembre 2010 17.56.49 CEST
*/

public interface BoxConfigurator extends BoxConfiguratorOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface BoxConfigurator
