package broker.init;


/**
* broker/init/BoxConfiguratorOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../idl/init.idl
* Monday, September 13, 2010 1:13:31 PM CEST
*/

public interface BoxConfiguratorOperations 
{
  String Configure (String config);
} // interface BoxConfiguratorOperations
