package broker.init;


/**
* broker/init/BoxConfigurator.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../idl/init.idl
* lunedì 18 ottobre 2010 10.53.25 CEST
*/

public interface BoxConfigurator extends BoxConfiguratorOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface BoxConfigurator
