package broker.init;


/**
* broker/init/BoxConfiguratorOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../idl/init.idl
* Sunday, September 26, 2010 2:23:32 PM CEST
*/

public interface BoxConfiguratorOperations 
{
  String Configure (String config);
} // interface BoxConfiguratorOperations
