package broker.init;


/**
* broker/init/CompetitionConfiguratorOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../idl/init.idl
* Thursday, September 23, 2010 1:31:48 AM CEST
*/

public interface CompetitionConfiguratorOperations 
{
  String Configure (String config);
} // interface CompetitionConfiguratorOperations
