package broker.init;


/**
* broker/init/CompetitionConfigurator.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../idl/init.idl
* Sunday, September 26, 2010 2:23:32 PM CEST
*/

public interface CompetitionConfigurator extends CompetitionConfiguratorOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface CompetitionConfigurator
