package broker.init;


/**
* broker/init/CompetitionConfiguratorOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../idl/init.idl
* giovedì 7 ottobre 2010 22.57.22 CEST
*/

public interface CompetitionConfiguratorOperations 
{
  String Configure (String config);
} // interface CompetitionConfiguratorOperations
