package broker.init;


/**
* broker/init/CompetitionConfiguratorOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../idl/init.idl
* martedì 28 settembre 2010 12.39.28 CEST
*/

public interface CompetitionConfiguratorOperations 
{
  String Configure (String config);
} // interface CompetitionConfiguratorOperations
