package broker.init;


/**
* broker/init/RegistrationHandler.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../idl/init.idl
* lunedì 11 ottobre 2010 16.12.42 CEST
*/

public interface RegistrationHandler extends RegistrationHandlerOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface RegistrationHandler
