package broker.init;


/**
* broker/init/RegistrationHandler.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../idl/init.idl
* Sunday, September 26, 2010 2:23:32 PM CEST
*/

public interface RegistrationHandler extends RegistrationHandlerOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface RegistrationHandler
