package broker.init;


/**
* broker/init/RegistrationHandlerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../idl/init.idl
* lunedì 11 ottobre 2010 16.12.42 CEST
*/

public interface RegistrationHandlerOperations 
{
  void Join_Competition (String competitorDescriptorFile, String boxCorbaLoc, org.omg.CORBA.StringHolder monitorCorbaLoc, org.omg.CORBA.ShortHolder competitorId, org.omg.CORBA.FloatHolder circuitLength, org.omg.CORBA.ShortHolder laps);
} // interface RegistrationHandlerOperations
