package broker.init;


/**
* broker/init/RegistrationHandler.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../idl/init.idl
* martedì 28 settembre 2010 12.09.36 CEST
*/

public interface RegistrationHandler extends RegistrationHandlerOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface RegistrationHandler
