
/**
* Competition_Monitor_Radio.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from competition_monitor_radio.idl
* Wednesday, August 25, 2010 9:51:31 AM CEST
*/

public interface Competition_Monitor_Radio extends Competition_Monitor_RadioOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Competition_Monitor_Radio
