
/**
* Competition_Monitor_Radio.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from competition_monitor_radio.idl
* Friday, August 27, 2010 7:23:49 PM CEST
*/

public interface Competition_Monitor_Radio extends Competition_Monitor_RadioOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Competition_Monitor_Radio
