
/**
* Competition_Monitor_RadioOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from competition_monitor_radio.idl
* Friday, August 27, 2010 7:23:49 PM CEST
*/

public interface Competition_Monitor_RadioOperations 
{
  String Get_CompetitorInfo (short lap, short sector, short id, org.omg.CORBA.FloatHolder time);
  float[] Get_CompetitionInfo (float timeInstant, org.omg.CORBA.StringHolder xmlInfo);
  String getBestLap ();
  String getBestSector (short index);
  boolean ready (short competitorId);
} // interface Competition_Monitor_RadioOperations
