 interface Competition_Monitor_Radio {
	string Get_CompetitorInfo(in short lap, in short sector, in short id, out float time);
	string Get_CompetitionInfo(in float timeInstant);
	string getBestLap();
	string getBestSector( in short index );
	boolean ready( in short competitorId );
};
