 interface Competition_Monitor_Radio {
	string getInfo(in short lap, in short sector, in short id, out float time);
	string getBestLap();
	string getBestSector( in short index );
	boolean ready( in short competitorId );
};
