
/**
* CompetitionConfigurator.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from competitionConfigurator.idl
* Tuesday, August 17, 2010 12:28:16 PM CEST
*/

public interface CompetitionConfigurator extends CompetitionConfiguratorOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface CompetitionConfigurator
