
/**
* CompetitionConfiguration.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from competitionConfiguration.idl
* Wednesday, July 21, 2010 10:41:13 PM CEST
*/

public interface CompetitionConfiguration extends CompetitionConfigurationOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface CompetitionConfiguration
