
/**
* CompetitionConfigurationHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from competitionConfiguration.idl
* venerdì 20 agosto 2010 22.19.03 CEST
*/

public final class CompetitionConfigurationHolder implements org.omg.CORBA.portable.Streamable
{
  public CompetitionConfiguration value = null;

  public CompetitionConfigurationHolder ()
  {
  }

  public CompetitionConfigurationHolder (CompetitionConfiguration initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CompetitionConfigurationHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CompetitionConfigurationHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CompetitionConfigurationHelper.type ();
  }

}
