
/**
* CompetitionConfiguratorOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from competitionConfigurator.idl
* venerdì 20 agosto 2010 22.18.56 CEST
*/

public interface CompetitionConfiguratorOperations 
{
  String Configure (String config);
} // interface CompetitionConfiguratorOperations
