
/**
* CompetitionConfigurationHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from competitionConfiguration.idl
* Wednesday, July 21, 2010 10:41:13 PM CEST
*/

abstract public class CompetitionConfigurationHelper
{
  private static String  _id = "IDL:CompetitionConfiguration:1.0";

  public static void insert (org.omg.CORBA.Any a, CompetitionConfiguration that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static CompetitionConfiguration extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (CompetitionConfigurationHelper.id (), "CompetitionConfiguration");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static CompetitionConfiguration read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_CompetitionConfigurationStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, CompetitionConfiguration value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static CompetitionConfiguration narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof CompetitionConfiguration)
      return (CompetitionConfiguration)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      _CompetitionConfigurationStub stub = new _CompetitionConfigurationStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static CompetitionConfiguration unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof CompetitionConfiguration)
      return (CompetitionConfiguration)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      _CompetitionConfigurationStub stub = new _CompetitionConfigurationStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
