
/**
* CompetitionConfigurationOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from competitionConfiguration.idl
* Wednesday, July 21, 2010 10:41:13 PM CEST
*/

public interface CompetitionConfigurationOperations 
{
  String Configure (String config);
} // interface CompetitionConfigurationOperations
