
/**
* CompetitionConfigurationOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from competitionConfiguration.idl
* venerdì 20 agosto 2010 22.19.03 CEST
*/

public interface CompetitionConfigurationOperations 
{
  String Configure (String config);
} // interface CompetitionConfigurationOperations
