
/**
* CompetitionConfiguratorHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from competitionConfigurator.idl
* Tuesday, August 17, 2010 12:28:16 PM CEST
*/

public final class CompetitionConfiguratorHolder implements org.omg.CORBA.portable.Streamable
{
  public CompetitionConfigurator value = null;

  public CompetitionConfiguratorHolder ()
  {
  }

  public CompetitionConfiguratorHolder (CompetitionConfigurator initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CompetitionConfiguratorHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CompetitionConfiguratorHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CompetitionConfiguratorHelper.type ();
  }

}
