
/**
* CompetitionConfiguration.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from competitionConfiguration.idl
* venerdì 20 agosto 2010 22.19.03 CEST
*/

public interface CompetitionConfiguration extends CompetitionConfigurationOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface CompetitionConfiguration
