
/**
* RegistrationHandler.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from registrationHandler.idl
* Wednesday, July 21, 2010 2:33:10 PM CEST
*/

public interface RegistrationHandler extends RegistrationHandlerOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface RegistrationHandler
